### PR TITLE
Feature/mocktable import from type

### PR DESCRIPTION
**Pull request by martinsmith1968**
I realise you have an outstanding PR for similar functionality. I didn't spot it before I started on this and it's a simpler approach to creating a mock table for a set of expected returned rows so maybe they could co-exist ?

Comments welcome

### CODE REVIEW

**Comment by dvoituron** [comment]
Hello,

Thanks for your PR... very interesting. I prefer your code where you've developed a method `MockTable.FromType<>` called from the DbMocker, and your code is very simple to use.

I've only two remarks:
1. Add a some **nullable properties** in your class `SimpleModel` to validate "NULL" values.
2. Move your tests to a file `DbMockTableFromTypeTests.cs` and your code to `MockTableFromType.cs` (partial class `MockTable`).

**Comment by martinsmith1968** [comment]
Hi Denis,

Thanks for those comments - all valid and useful.
I've made the changes as you suggested and updated the branch and PR.

There are some failing tests in areas that I haven't touched (they fail in
master branch too) so I haven't done anything with those in case someone
else was already looking at them.

Thanks

Martin

**Comment by dvoituron** [comment]
Thanks for your great job.
I've merged your PR in the master branch. In some days, I'll published it in a new NuGet package.

**Comment by dvoituron** [comment]
Can you tell me more about test failed? In my environment, all tests passed successfully.

**Comment by martinsmith1968** [comment]
Thanks for the merge and credit :-)
Looks like my git-config settings don't normalize the line endings on checkout or checkin - so they are left as-is. Some of the Test cs files have in-line strings covering more than one line so the code looking for Environment.NewLine doesn't detect them properly. I could just patch up the inline strings in the tests, but I thought it would be better to make the line ending detection consistent across the code that needs it. I've put another PR up - see what you think.

**Pull request merged**
