### PR TITLE
Add multiple result sets.

### PR DESCRIPTION
**Pull request by stop-cran**
Sometimes one has to mock stored procedures with multiple result sets. Mocking multiple tables going to look like below (see also unit tests):
```C#
MockTable table1 = MockTable.WithColumns("Col1", "Col2")
                     .AddRow(11, 12);
conn.Mocks
    .WhenAny()
    .ReturnsTable(table1);

MockTable table2 = MockTable.WithColumns("Col3", "Col4")
         .AddRow("aa", 3.4);
conn.Mocks
    .WhenAny()
    .ReturnsTable(table2);
```

### CODE REVIEW

**Comment by dvoituron** [comment]
Interresting. Why not to add a new method **ReturnsDataset(IEnumerable<MockTable>)**?
So, it's will be possible to use multiple **ReturnsTable** like you propose, and also this new method.

**Comment by stop-cran** [comment]
Yes, a new method is better. My current code introduce breaking changes in conditions logic, which is not good. Wil try to add the new method.

**Comment by stop-cran** [comment]
Added the `ReturnsDataset` method. It acceptes an array though, to follow the overall convention. Maybe it makes sense to change the convention as a whole - accept `IEnumerable<T>` everywhere instead of arrays, preferably use immutable objects, etc.

**Comment by dvoituron** [comment]
Indeed, it's would be better using `IEnumerable<T>`.
I'll accept your PR and I'll refactor that :-)
Thanks for your job.
I'll publish a new nuget version with your new feature in some hours.

**Comment by dvoituron** [comment]
The Nuget package is published: https://www.nuget.org/packages/DbMocker/1.7.0-Preview1
After a validation phase, I'll published the final version.
Thanks for your work.

**Pull request merged**
